// ============================================================================
// SHARED EXPORT ENGINE
//
// One engine, one visual language, three document types:
//   - SBAR passport (triage session)
//   - Period history sheet (CSV + PDF)
//   - Pregnancy/period doctor-shareable summary
//
// Do not build a second PDF pipeline for a new module — extend
// buildDocument() with a new section renderer instead.
// ============================================================================

import { jsPDF } from 'jspdf';
import type { TriageSession, PeriodLog, User, CycleStats } from '../types';

const BRAND = {
  title: 'Emergency AI — Health Record',
  accent: [59, 178, 246] as [number, number, number],
  muted: [143, 160, 192] as [number, number, number],
  dark: [18, 27, 46] as [number, number, number],
};

function newDoc(title: string) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, 0, 595, 90, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text(BRAND.title, 40, 40);
  doc.setFontSize(12);
  doc.setTextColor(...BRAND.accent);
  doc.text(title, 40, 62);
  doc.setTextColor(0, 0, 0);
  return doc;
}

function footer(doc: jsPDF) {
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.muted);
  doc.text('Generated by Emergency AI — for informational support, not a substitute for professional medical diagnosis.', 40, 800);
}

/** SBAR passport — a shareable/printable summary a patient brings to a doctor */
export function exportSBARPassport(session: TriageSession, user: User): Blob {
  const doc = newDoc('SBAR Passport — Triage Summary');
  let y = 120;
  const line = (label: string, value: string) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(label, 40, y);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(value || '—', 420);
    doc.text(lines, 150, y);
    y += 18 * Math.max(1, lines.length);
  };

  line('Patient', user.name ?? 'Guest user');
  line('District', user.district ?? '—');
  line('Date', new Date(session.createdAt).toLocaleString());
  y += 10;

  doc.setFont('helvetica', 'bold');
  doc.text('S — Situation', 40, y); y += 16;
  doc.setFont('helvetica', 'normal');
  doc.text(doc.splitTextToSize(`Reported severity: ${session.finalSeverity}`, 500), 40, y); y += 30;

  doc.setFont('helvetica', 'bold');
  doc.text('B — Background', 40, y); y += 16;
  doc.setFont('helvetica', 'normal');
  const bg = user.medicalHistory
    ? `Allergies: ${user.medicalHistory.allergies.join(', ') || 'none reported'}. Chronic conditions: ${user.medicalHistory.chronicConditions.join(', ') || 'none reported'}.`
    : 'No medical history on file.';
  doc.text(doc.splitTextToSize(bg, 500), 40, y); y += 40;

  doc.setFont('helvetica', 'bold');
  doc.text('A — Assessment', 40, y); y += 16;
  doc.setFont('helvetica', 'normal');
  doc.text(doc.splitTextToSize(session.localPass.rationale + (session.aiPass ? ' ' + session.aiPass.rationale : ''), 500), 40, y); y += 50;

  doc.setFont('helvetica', 'bold');
  doc.text('R — Recommendation', 40, y); y += 16;
  doc.setFont('helvetica', 'normal');
  doc.text(doc.splitTextToSize(session.recommendation, 500), 40, y);

  footer(doc);
  return doc.output('blob');
}

/** Period history — doctor-shareable PDF, same layout language as SBAR */
export function exportPeriodReportPDF(logs: PeriodLog[], stats: CycleStats, user: User): Blob {
  const doc = newDoc('Period History Summary');
  let y = 120;

  doc.setFont('helvetica', 'bold');
  doc.text('Cycle statistics', 40, y); y += 20;
  doc.setFont('helvetica', 'normal');
  doc.text(`Average cycle length: ${stats.averageCycleLengthDays} days`, 40, y); y += 16;
  doc.text(`Average period length: ${stats.averagePeriodLengthDays} days`, 40, y); y += 16;
  doc.text(`Predicted next start: ${stats.predictedNextStart}`, 40, y); y += 16;
  doc.text(`Predicted fertile window: ${stats.predictedFertileWindow[0]} – ${stats.predictedFertileWindow[1]}`, 40, y); y += 30;

  doc.setFont('helvetica', 'bold');
  doc.text('Cycle history', 40, y); y += 20;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  logs.slice(0, 25).forEach((log) => {
    if (y > 760) { doc.addPage(); y = 60; }
    const flowText = `${log.cycleStartDate} → ${log.cycleEndDate ?? 'ongoing'} · flow: ${log.flowIntensity}${log.symptoms.length ? ' · symptoms: ' + log.symptoms.join(', ') : ''}`;
    doc.text(flowText, 40, y);
    y += 14;
  });

  footer(doc);
  return doc.output('blob');
}

/** CSV export — one-click exportable date sheet */
export function exportPeriodCSV(logs: PeriodLog[]): Blob {
  const header = 'cycle_start,cycle_end,flow_intensity,symptoms,mood\n';
  const rows = logs
    .map((l) => [l.cycleStartDate, l.cycleEndDate ?? '', l.flowIntensity, `"${l.symptoms.join('; ')}"`, l.mood ?? ''].join(','))
    .join('\n');
  return new Blob([header + rows], { type: 'text/csv' });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
