import { jsPDF } from 'jspdf';
import type { TriageSession, PeriodLog, User, CycleStats } from '../types';

const BRAND = {
  title: 'Emergency AI — Health Record',
  accent: [232, 90, 145] as [number, number, number],
  muted: [100, 116, 139] as [number, number, number],
  dark: [15, 23, 42] as [number, number, number],
};

function newDoc(title: string) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, 0, 595, 90, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text(BRAND.title, 40, 40);
  doc.setFontSize(12);
  doc.setTextColor(...BRAND.accent);
  doc.text(title, 40, 62);
  doc.setTextColor(0, 0, 0);
  return doc;
}

function footer(doc: jsPDF) {
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.muted);
  doc.text('Generated by Emergency AI — for informational support, not a substitute for professional medical diagnosis.', 40, 800);
}

/** SBAR passport — shareable/printable summary for medical consultation */
export function exportSBARPassport(session: TriageSession, user: User): Blob {
  const doc = newDoc('SBAR Passport — Medical Triage Summary');
  let y = 120;
  const line = (label: string, value: string) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(label, 40, y);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(value || '—', 420);
    doc.text(lines, 150, y);
    y += 18 * Math.max(1, lines.length);
  };

  line('Patient Name', user.name ?? 'Guest User');
  line('District Location', user.district ?? 'Not specified');
  line('Emergency Contact', user.emergencyContact ? `${user.emergencyContact.phone} (${user.emergencyContact.relationship})` : 'Not recorded');
  line('Record Date', new Date(session.createdAt).toLocaleString());
  y += 10;

  // S — Situation
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('S — Situation', 40, y); y += 16;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(doc.splitTextToSize(`Triage Severity Level: ${session.finalSeverity}. Module: ${session.module.toUpperCase()}`, 500), 40, y); y += 30;

  // B — Background (Includes User Medical History)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('B — Background (Medical History)', 40, y); y += 16;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const historyParts: string[] = [];
  if (user.medicalHistoryText) historyParts.push(`Recorded History: ${user.medicalHistoryText}`);
  if (user.medicalHistory?.allergies?.length) historyParts.push(`Allergies: ${user.medicalHistory.allergies.join(', ')}`);
  if (user.medicalHistory?.chronicConditions?.length) historyParts.push(`Conditions: ${user.medicalHistory.chronicConditions.join(', ')}`);
  const bgText = historyParts.length > 0 ? historyParts.join(' | ') : 'No prior medical history or chronic conditions recorded on file.';
  const bgLines = doc.splitTextToSize(bgText, 500);
  doc.text(bgLines, 40, y);
  y += 18 * Math.max(1, bgLines.length) + 15;

  // A — Assessment
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('A — Assessment', 40, y); y += 16;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const assessmentText = session.localPass.rationale + (session.aiPass ? ' ' + session.aiPass.rationale : '');
  const assessLines = doc.splitTextToSize(assessmentText, 500);
  doc.text(assessLines, 40, y);
  y += 18 * Math.max(1, assessLines.length) + 15;

  // R — Recommendation
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('R — Recommendation', 40, y); y += 16;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const recLines = doc.splitTextToSize(session.recommendation, 500);
  doc.text(recLines, 40, y);

  footer(doc);
  return doc.output('blob');
}

export function exportPeriodReportPDF(logs: PeriodLog[], stats: CycleStats, user: User): Blob {
  const doc = newDoc('Period History Summary');
  let y = 120;

  doc.setFont('helvetica', 'bold');
  doc.text('Cycle statistics', 40, y); y += 20;
  doc.setFont('helvetica', 'normal');
  doc.text(`Average cycle length: ${stats.averageCycleLengthDays} days`, 40, y); y += 16;
  doc.text(`Average period length: ${stats.averagePeriodLengthDays} days`, 40, y); y += 16;
  doc.text(`Predicted next start: ${stats.predictedNextStart}`, 40, y); y += 16;
  doc.text(`Predicted fertile window: ${stats.predictedFertileWindow[0]} – ${stats.predictedFertileWindow[1]}`, 40, y); y += 30;

  doc.setFont('helvetica', 'bold');
  doc.text('Cycle history', 40, y); y += 20;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  logs.slice(0, 25).forEach((log) => {
    if (y > 760) { doc.addPage(); y = 60; }
    const flowText = `${log.cycleStartDate} → ${log.cycleEndDate ?? 'ongoing'} · flow: ${log.flowIntensity}${log.symptoms.length ? ' · symptoms: ' + log.symptoms.join(', ') : ''}`;
    doc.text(flowText, 40, y);
    y += 14;
  });

  footer(doc);
  return doc.output('blob');
}

export function exportPeriodCSV(logs: PeriodLog[]): Blob {
  const header = 'cycle_start,cycle_end,flow_intensity,symptoms,mood\n';
  const rows = logs
    .map((l) => [l.cycleStartDate, l.cycleEndDate ?? '', l.flowIntensity, `"${l.symptoms.join('; ')}"`, l.mood ?? ''].join(','))
    .join('\n');
  return new Blob([header + rows], { type: 'text/csv' });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
